version: "3.8"

services:
  osrm:
    image: osrm/osrm-backend
    container_name: open-vayra-cities-osrm
    restart: "no"
    ports:
      - "5000:5000"
    volumes:
      - ../../../data/routing/osrm:/data
    command: "osrm-routed --algorithm mld /data/${OSRM_FILE:-hvv-mvp/hvv-mvp.osrm}"
